name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude-code:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Process with Claude
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # This is a placeholder for Claude integration
          # You'll need to implement the actual Claude API call here
          # or use the official Claude GitHub App when available
          echo "Claude integration placeholder - implement API calls here"
          
      - name: Update SVG Diagrams
        if: contains(github.event.comment.body, 'diagram') || contains(github.event.comment.body, 'svg')
        run: |
          # Rebuild Hugo site if diagrams were updated
          if git diff --name-only | grep -q "\.svg$"; then
            echo "SVG files were modified, rebuilding site..."
            hugo --gc --minify
          fi